version: '3.7'

services:
 crawler_service:
    container_name: Crawler
    depends_on:
      - postgre_db_service
      - rabbitmq3
    ports:
      - 8080:8080
      - 80:80
      - 81:81
    build: 
      context: ./
      dockerfile: Crawler/Crawler.Main/Dockerfile    
    restart: always
    
 postgre_db_service:    
    container_name: PostgreSQL
    image: postgres:latest    
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qscwdv1!
      POSTGRES_DB: cbrhangfire

 rabbitmq3:
    container_name: RabbitMQ
    image: rabbitmq:3-management
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    ports:
        # AMQP protocol port
        - 5672:5672
        # HTTP management UI
        - 15672:15672

 converter:
   build: 
     context: ./
     dockerfile: Converter/Converter.Main/Dockerfile
   container_name: Converter
   restart: always
   depends_on:
     - rabbitmq3
     - storage
     - crawler_service

 storage:
     build: 
       context: ./
       dockerfile: Storage/Storage.Main/Dockerfile
     container_name: Storage
     restart: always
     depends_on:
       - postgre_db_service
       - rabbitmq3
       - crawler_service